### ISSUE TITLE
Project Management Report

### ISSUE THREAD

**Issue by onemoongit** [caucse19/SE_TermProj#18]
Documents/PMR/ProgressHistory -> Documents/ProjectManagementReport 로 변경할 예정입니다.

Project Managements Report 에 적을 Experience 는 여기에다가 남겨주시면 됩니다~

**Comment by ParkJinHyuk** [comment]
It was a good team project experience. I felt that when i was working on the previous projects, we just got together and divided into assignment. But I feel that the project that we have conducted this time is systematically proceeding.  Instead of passing code using kakao, notepad, we use github to share code with our team members. It was a new experience not to start coding without any plans but to draw diverse diagrams, write document and then code in a systematic framework and process. I think that this experience with a team project will help when i join a big team project later.

**Comment by wnsgh1030** [comment]
생각보다 어려웠고 기존 팀 프로젝트보다 더 복잡했다.
이번 프로젝트는 단지 과제제출이 목적이 아닌 이 프로그램을 사용하는 사용자의 입장도 생각하게 되었고 프로그램을 짤 때 좀 더 체계적으로 짜는 방법을 배웠다. 또한 JUNIT 이라는 test tool 의 사용법도 배웠다. 이 부분 뿐만아니라 github 사용법 , SRS , diagram 을 만드는 법 등 배워 기존 수업과는 새로운 경험을 했다.

**Comment by insu0929** [comment]
실제 현장에서 어떠한 방식으로 프로젝트가 진행되는지 배울 수 있는 기회였습니다.
프로젝트 시작 단계에서 어떻게 이해관계자들과 협동하면서 요구사항들을 맞춰가는지
조금은 경험할 수  있었습니다. 개발을 의뢰하는 사람들로부터 협상한 내용들을 또 개발자들끼리
어떠한 방식으로 조율해서  맞춰나가야하는지 느낄 수 있었습니다.

여태까지는 waterfall 모델에 가까운 구현 방식으로만 코딩을 하였지만,
규모가 커지는 프로젝트와 구성원들이 많을 경우 과목에서 배운 소프트웨어 개발 방식을
적용하는 경험을 할 수 있어서 매우 색달랐습니다.

또한 GitHub라는 새로운 버전 관리 프로그램을 사용할 수 있어서 개인적으로 매우 유익하다고
느꼈고, 앞으로 하게 될 전공 관련 활동을 해당 툴에 최대한 남겨야겠다는 생각이 들었습니다.

**Comment by danny7742** [comment]
프로젝트를 제작할때, 코드보다 문서를 먼저 작업했던 적은 이번이 처음이다. 
코딩 이전에 간략한 SRS 문서, 다이어그램 등의 작성을 통해 프로그램의 구성, 요구사항 등을 팀원 모두가 공유하고 난 후 프로젝트가 진행되니, 프로젝트가 단계 별로 수월하게 진행됨을 느낄 수 있었다. 
또한, 작년에도 깃허브를 통하여 팀 프로젝트를 진행하였는데, 그 때는 단순히 깃허브로 프로젝트를 진행하였다 라고 느꼇던 반면 이번 프로젝트는 정말 깃허브라는 프로그램을 어떻게 활용하는지에 대해 몸소 체험할 수 있었다. 
소프트웨어 공학 수업시간에 배웠던 내용들을 실제로 어떻게 응용하는지 전혀 감도 오지 않았는데, 이렇게 여러 팀원들과 함께 그 내용들을 실현하게 되니 그제서야 머릿속의 퍼즐 조각이 맞춰진 것 같다. 소프트웨어공학 수업이 왜 컴퓨터공학부의 핵심 과목인지를 느낄 수 있었다. 학교 졸업 후 실무에서 이번 경험이 큰 도움이 되었으면 좋겠다.
